pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building Robot Framework'
            }
        } 
        stage('Run Avatar Test') {
            steps {
                echo 'Run Show Message Test'
                bat 'robot -d log --i avatar_test tests/github_test_cases.robot'
            }
        }
        stage('Run Show Message Test') {
            steps {
                echo 'Run Show Message Test'
                bat 'robot -d log --i show_message tests/github_test_cases.robot'
            }
        }
    }
}